# Generated by Django 4.2.7 on 2025-04-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.IntegerField()),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "API Request Log",
                "verbose_name_plural": "API Request Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
