# Generated by Django 4.2.7 on 2025-04-22 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        help_text="URL to the JSON file to process", max_length=1000
                    ),
                ),
                (
                    "output_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 key for output file",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("total_clauses", models.IntegerField(default=0)),
                ("total_definitions", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Processing Job",
                "verbose_name_plural": "Processing Jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
